/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsFooter {
    }
    interface DsHeader {
        "dsTitle": string;
    }
}
declare global {
    interface HTMLDsFooterElement extends Components.DsFooter, HTMLStencilElement {
    }
    var HTMLDsFooterElement: {
        prototype: HTMLDsFooterElement;
        new (): HTMLDsFooterElement;
    };
    interface HTMLDsHeaderElement extends Components.DsHeader, HTMLStencilElement {
    }
    var HTMLDsHeaderElement: {
        prototype: HTMLDsHeaderElement;
        new (): HTMLDsHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "ds-footer": HTMLDsFooterElement;
        "ds-header": HTMLDsHeaderElement;
    }
}
declare namespace LocalJSX {
    interface DsFooter {
    }
    interface DsHeader {
        "dsTitle"?: string;
    }
    interface IntrinsicElements {
        "ds-footer": DsFooter;
        "ds-header": DsHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-footer": LocalJSX.DsFooter & JSXBase.HTMLAttributes<HTMLDsFooterElement>;
            "ds-header": LocalJSX.DsHeader & JSXBase.HTMLAttributes<HTMLDsHeaderElement>;
        }
    }
}
