apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - name: correlationId
          matcherRegex: '"correlationId":"([^"]+)"'
          url: 'http://localhost:3001/urls?correlationId=$1'
          datasourceUid: loki
        - name: requestId
          matcherRegex: '"requestId":"([^"]+)"'
          url: 'http://localhost:3001/urls?requestId=$1'
          datasourceUid: loki
