apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-hpa-poc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-hpa-poc
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
