apiVersion: v1
kind: Service
metadata:
  name: nodejs-scaling-service
  labels:
    app: nodejs-scaling-poc
spec:
  type: NodePort
  selector:
    app: nodejs-scaling-poc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
