CREATE TABLE IF NOT EXISTS products (
    id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name  TEXT        NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    stock INTEGER     NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_products_name ON products (name);