CREATE TABLE IF NOT EXISTS brtax_user (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  cpf VARCHAR(11) NOT NULL UNIQUE,
  password VARCHAR(32) NOT NULL,
  type VARCHAR(50) NOT NULL
);
