spring.application.name=email
server.port=8001

# mongodb
spring.data.mongodb.uri=mongodb://localhost:27017/payment_service_mongo
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=root
spring.data.mongodb.password=root
spring.data.mongodb.database=payment_service_mongo