-- 1 Crie um banco de dados com o nome de CLINICA.
CREATE DATABASE CLINICA
GO
USE CLINICA
GO

-- 2. Execute os comandos DDL necess�rios para criar o modelo acima.
CREATE TABLE MEDICO (
ID_MEDICO INT,
SALARIO NUMERIC(10,2),
NOME VARCHAR(50),
CRM INT,
BENEFICIO NUMERIC(10,2),
ID_ESPECIALIDADE INT,
CONSTRAINT MEDICO_PK PRIMARY KEY (ID_MEDICO))

CREATE TABLE PACIENTE (
ID_PACIENTE INT,
ESTADO CHAR(2),
NOME VARCHAR(50),
IDADE INT,
CONSTRAINT PACIENTE_PK PRIMARY KEY (ID_PACIENTE))

CREATE TABLE QUARTO (
ID_QUARTO INT,
NUMERO INT,
CONSTRAINT QUARTO_PK PRIMARY KEY (ID_QUARTO))

CREATE TABLE ESPECIALIDADE (
ID_ESPECIALIDADE INT,
DESCRICAO VARCHAR(50),
CONSTRAINT ESPECIALIDADE_PK PRIMARY KEY (ID_ESPECIALIDADE))

CREATE TABLE INTERNACAO (
ID_MEDICO INT,
ID_PACIENTE INT,
DATA_HORA DATETIME,
ID_QUARTO INT)

--3 Na tabela MEDICO crie uma constraint cascade para exclusão e atualização no campo ID_ESPECIALIDADE.
ALTER TABLE MEDICO
ADD CONSTRAINT ID_ESPECIALIDADE_FK 
FOREIGN KEY (ID_ESPECIALIDADE) 
REFERENCES ESPECIALIDADE (ID_ESPECIALIDADE)
ON DELETE CASCADE 
ON UPDATE CASCADE

-- 4 Na tabela MEDICO crie uma constraint para CRM como chave candidata.
ALTER TABLE MEDICO
ADD CONSTRAINT CRM_UNIQUE 
UNIQUE (CRM)

--5 Na tabela MEDICO crie uma contraint para validar que o BENEFICIO deve ser menor que o SALARIO.
ALTER TABLE MEDICO 
ADD CONSTRAINT BENEFICIO_CK
CHECK (BENEFICIO < SALARIO)

--6 Na tabela MEDICO crie uma contraint para validar que o SALARIO deve ser maior que 0 (zero).
ALTER TABLE MEDICO
ADD CONSTRAINT SALARIO_CK
CHECK (SALARIO > 0)

--7 Na tabela PACIENTE crie uma contraint para NOME como chave candidata.
ALTER TABLE PACIENTE 
ADD CONSTRAINT NOME_UNIQUE
UNIQUE (NOME)

--8 Na tabela PACIENTE crie uma contraint para validar que IDADE seja um valor entre 0 e 100.
ALTER TABLE PACIENTE 
ADD CONSTRAINT IDADE_CK
CHECK (IDADE >= 0 AND IDADE <= 100)

--9 Na tabela PACIENTE crie uma contraint para validar que ESTADO seja um dos seguintes estados: RS, SC, PR.
ALTER TABLE PACIENTE
ADD CONSTRAINT ESTADO_CK
CHECK (ESTADO IN ('RS', 'SC', 'PR'))

--10 Na tabela QUARTO crie uma contraint para NUMERO como chave candidata.
ALTER TABLE QUARTO
ADD CONSTRAINT NUMERO_UNIQUE
UNIQUE (NUMERO)

--11 Na tabela ESPECIALIDADE crie uma contraint para DESCRICAO como chave candidata.
ALTER TABLE ESPECIALIDADE 
ADD CONSTRAINT DESCRICAO_UNIQUE
UNIQUE (DESCRICAO)

--12 Na tabela INTERNACAO crie uma constraint para chave primaria composta entre ID_MEDICO, ID_PACIENTE e DATA_HORA
ALTER TABLE INTERNACAO
ALTER COLUMN DATA_HORA DATETIME NOT NULL

ALTER TABLE INTERNACAO
ALTER COLUMN ID_MEDICO INT NOT NULL

ALTER TABLE INTERNACAO
ALTER COLUMN ID_PACIENTE INT NOT NULL

ALTER TABLE INTERNACAO 
ADD CONSTRAINT INTERNACAO_PK
PRIMARY KEY (ID_MEDICO, ID_PACIENTE, DATA_HORA)

--13 Na tabela INTERNACAO crie uma constraint cascade para exclusão e atualização no campo 
--ID_PACIENTE.
ALTER TABLE INTERNACAO
ADD CONSTRAINT ID_PACIENTE_FK
FOREIGN KEY (ID_PACIENTE)
REFERENCES PACIENTE (ID_PACIENTE)
ON DELETE CASCADE
ON UPDATE CASCADE

--14 Na tabela INTERNACAO crie uma constraint 
--SET DEFAULT para exclusão e atualização no 
--campo ID_MEDICO.

ALTER TABLE INTERNACAO
ADD CONSTRAINT ID_MEDICO_FK
FOREIGN KEY (ID_MEDICO)
REFERENCES MEDICO (ID_MEDICO)
ON DELETE SET DEFAULT
ON UPDATE SET DEFAULT


--15 Na tabela INTERNACAO crie uma constraint SET NULL para exclusão e atualização no campo ID_QUARTO.

ALTER TABLE INTERNACAO
ADD CONSTRAINT ID_QUARTO_FK
FOREIGN KEY (ID_QUARTO)
REFERENCES QUARTO (ID_QUARTO)
ON DELETE SET NULL
ON UPDATE SET NULL

--16 Na tabela INTERNACAO crie um valor DEFAULT 100 para o campo ID_MEDICO

ALTER TABLE INTERNACAO
ADD CONSTRAINT DEFAULT_ID_MEDICO
DEFAULT 100 FOR ID_MEDICO

BEGIN TRANSACTION
INSERT INTO ESPECIALIDADE
VALUES (1, 'OTORRINO')
COMMIT
SELECT * FROM ESPECIALIDADE

BEGIN TRANSACTION 
INSERT INTO ESPECIALIDADE
VALUES (2, 'CARDIOLOGISTA')
UPDATE ESPECIALIDADE
SET DESCRICAO = 'OTORRINOLOGISTA'
WHERE ID_ESPECIALIDADE = 1
SAVE TRANSACTION PONTO1
INSERT INTO ESPECIALIDADE
VALUES (3, 'PEDIATRA')
ROLLBACK TRANSACTION PONTO1
SELECT * FROM ESPECIALIDADE
COMMIT
